DoubleArray:doubleArray.o arrayPermutation.o
	gcc doubleArray.o arrayPermutation.o

arrayPermutation.o:arrayPermutation.c
	gcc -c arrayPermutation.c -o arrayPermutation.o

doubleArray.o:doubleArray.c
	gcc -c doubleArray.c -o doubleArray.o

clean:
	@rm -rf *.o DoubleArray